CREATE TABLE `board_member` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`category` text NOT NULL,
	`membership` text,
	`roles` text NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`revision` integer DEFAULT 1 NOT NULL
);

--> statement-breakpoint
-- Preserve the existing public history when moving it into D1.
INSERT INTO board_member (id, name, category, membership, roles, sort_order) VALUES
('board-history-001', 'Brigt A.T Håvardstun', 'founder', NULL, '[{"title":"Co-founder"}]', 0),
('board-history-002', 'Sandra Lekve', 'founder', NULL, '[{"title":"Co-founder"}]', 1),
('board-history-003', 'Vegard Jensløkken', 'founder', NULL, '[{"title":"Co-founder"}]', 2),
('board-history-004', 'Eivind D. Halderaker', 'founder', NULL, '[{"title":"Co-founder"}]', 3),
('board-history-005', 'Erik Fjelltveit Nyhuus', 'current', NULL, '[{"title":"Leder"}]', 4),
('board-history-006', 'Steffen Andre Pettersen', 'current', NULL, '[{"title":"Sosialansvarlig"}]', 5),
('board-history-007', 'Siren Bjorøy', 'current', NULL, '[{"title":"Bookingansvarlig"}]', 6),
('board-history-008', 'Ole Straumland', 'current', NULL, '[{"title":"Frivilligansvarlig"}]', 7),
('board-history-009', 'August Ebne Røeggen', 'current', NULL, '[{"title":"Nestleder"}]', 8),
('board-history-010', 'Sturla Rognskog Mella', 'current', '{"start":"Høst 2025"}', '[{"title":"Frivilligansvarlig og webansvarlig","period":{"start":"Vår 2026"}},{"title":"Assistent for frivilligansvarlig","period":{"start":"Høst 2025","end":"Høst 2025"}}]', 9),
('board-history-011', 'Tord Vikøren Vikestad', 'current', '{"start":"Høst 2025"}', '[{"title":"Bygg/admin","period":{"start":"Høst 2025"}}]', 10),
('board-history-012', 'Henrik Sætre Breivik', 'current', '{"start":"Høst 2025"}', '[{"title":"Quiz- og arrangementsansvarlig","period":{"start":"Høst 2025"}}]', 11),
('board-history-013', 'Anna Sviland', 'current', '{"start":"Høst 2026"}', '[]', 12),
('board-history-014', 'Anna Valencia Fari', 'current', '{"start":"Høst 2026"}', '[]', 13),
('board-history-015', 'Oddmund Gullbrå Steinsland', 'current', '{"start":"Høst 2026"}', '[]', 14),
('board-history-016', 'Maya Shantseva', 'current', '{"start":"Høst 2026"}', '[]', 15),
('board-history-017', 'Torjus Berntsen', 'current', '{"start":"Høst 2026"}', '[]', 16),
('board-history-018', 'Mina Tolfsen', 'past', NULL, '[]', 17),
('board-history-019', 'Ask Rud Persson', 'past', NULL, '[]', 18),
('board-history-020', 'Palma Rud Persson', 'past', NULL, '[]', 19),
('board-history-021', 'Sigurd Johnsen Setså', 'past', NULL, '[]', 20),
('board-history-022', 'Erlend Raa Vågset', 'past', NULL, '[]', 21),
('board-history-023', 'Sofia Hestenes Eika', 'past', NULL, '[]', 22),
('board-history-024', 'Kristoffer Borg Nilsen', 'past', NULL, '[]', 23),
('board-history-025', 'Lars Lismoen', 'past', NULL, '[]', 24),
('board-history-026', 'Yoeri Otten', 'past', NULL, '[]', 25),
('board-history-027', 'Eirik Øygard', 'past', NULL, '[]', 26),
('board-history-028', 'Arne Natskår', 'past', NULL, '[]', 27),
('board-history-029', 'Alexander Alf Iversen', 'past', NULL, '[]', 28),
('board-history-030', 'Henrik Trondseth', 'past', NULL, '[]', 29),
('board-history-031', 'Emil Johannessen', 'past', NULL, '[]', 30),
('board-history-032', 'Andre Normann', 'past', NULL, '[]', 31),
('board-history-033', 'Sofie Nhu Nguyen', 'past', NULL, '[]', 32),
('board-history-034', 'Simen Hauge Østbø', 'past', NULL, '[]', 33),
('board-history-035', 'Stian Munkejord', 'past', NULL, '[]', 34),
('board-history-036', 'Gard Heine Kalland', 'past', NULL, '[]', 35),
('board-history-037', 'Lars Bysheim', 'past', NULL, '[]', 36),
('board-history-038', 'Lars Haukland', 'past', NULL, '[]', 37),
('board-history-039', 'Eirik Rekve Thorsheim', 'past', NULL, '[]', 38),
('board-history-040', 'Tony Bao Lam', 'past', '{"end":"Vår 2026"}', '[{"title":"Innkjøp","period":{"end":"Vår 2026"}}]', 39),
('board-history-041', 'Lene Soltveit', 'past', '{"end":"Vår 2026"}', '[{"title":"Økonomiansvarlig","period":{"end":"Vår 2026"}}]', 40),
('board-history-042', 'Ole Magnus Fon Johnsen', 'past', '{"end":"Vår 2026"}', '[{"title":"Webansvarlig","period":{"end":"Vår 2026"}}]', 41),
('board-history-043', 'Fredrik Hast Sørli', 'past', '{"start":"Høst 2025","end":"Vår 2026"}', '[{"title":"Økonomiassistent","period":{"start":"Høst 2025","end":"Vår 2026"}}]', 42);
