name: 💚 CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/programmerbar
  FEIDE_CLIENT_ID: test
  FEIDE_CLIENT_SECRET: test
  FEIDE_REDIRECT_URI: http://localhost:8000/auth/feide/callback
  ADMIN_KEY: test-admin-key
  PUBLIC_GITHUB_SHA: ${{ github.sha }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  PUBLIC_VAPID_PUBLIC_KEY: ${{ secrets.PUBLIC_VAPID_PUBLIC_KEY }}
  VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
  VAPID_SUBJECT: "mailto:web@programmerbar.no"
  PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY: 1x00000000000000000000AA
  CLOUDFLARE_TURNSTILE_SITE_SECRET: 1x0000000000000000000000000000000AA

jobs:
  ci:
    name: 💚 Run CI
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Checkout
        uses: actions/checkout@v6

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: 🐢 Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔵 Check
        run: pnpm check

      - name: 🚦 Lint
        run: pnpm lint

      - name: ⚡ Format check
        run: pnpm format:check

      - name: 🚀 Build
        run: pnpm build
